### ISSUE TITLE
Audio Support?

### ISSUE THREAD

**Issue by hybridherbst** [hecomi/uNvEncoder#1]
This plugin looks very promising for fast video capture.
Would it be possible for you to add audio support, either from system capture or directly from Unity audio output?
Thanks!

**Comment by hecomi** [comment]
Sorry for my late reply...
NvEncoder does nothing about Audio, so I don't have a plan to support Audio encoding in uNvEncoder to keep it simple.

**Comment by hybridherbst** [comment]
Thanks for the reply. Do you have an idea on how/where I should look if the goal is to record sync video+audio, with the video part being nicely handled by uNvEncoder?

**Comment by hecomi** [comment]
Unity Technologies Japan has released FrameCapturer: https://github.com/unity3d-jp/FrameCapturer
MovieRecorder can record both FrameBuffer and Audio. If your goal is recording them, it'll be a better solution.
