### ISSUE TITLE
Decoding / Streaming video live?

### ISSUE THREAD

**Issue by guiglass** [hecomi/uNvEncoder#5]
Thanks for making this plugin! I have a question how to use the byte data. Can it only be used as a pre-recorded .h264 file or is there a way to stream this data to another Unity project?

Sorry this question is not a actual issue, but I am having a lot of trouble sending compressed video to another Unity project and was wondering would it be possible to use uNvEncoder for live stream?

**Comment by hecomi** [comment]
This repository does not include decoding functions or protocols for sending data to remote processes.

Tests to encode the data in real time, send the data to another PC via UDP, and decode it on that PC were done in the following repository.

- https://github.com/hecomi/UnityRemoteDesktopDuplication

It uses [uNvPipe](https://github.com/hecomi/uNvPipe), which is a simple NVIDIA's NvPipe wrapper that can encode and decode textures (uNvEncoder has less overhead when it comes to encoding). There are a few bugs, but I hope this is helpful.
